### ISSUE TITLE
Crashs on clicking Refresh on Unit Journal tab

### ISSUE THREAD

**Issue by ryuheechul** [plrigaux/sysd-manager#1]
Just started using it, nice UI and working very well for the purpose 👍🏼.

One issue, I'm experiencing is that it crashes on clicking Refresh button on Unit Journal tab.

The version number is 0.1.10, installed via flatpak and on a NixOS and D-Bus is enabled to `org.freedesktop.Flatpak` via flatseal.

**Comment by plrigaux** [comment]
Thanks for your feedback. 

I will take a look.

**Comment by plrigaux** [comment]
The new version 1.3.0 might solve the issue.

- The journal events are now fetched in another thread,
- the way the coloring is applied on journal events has been changed 
- A config has been put in place to limit the number of log events (some can be huge).

**Comment by ryuheechul** [comment]
confirmed that there is no more crashes after upgrading to 1.3.0. Thanks!
